document.addEventListener('DOMContentLoaded', () => {
    const partnerForm = document.getElementById('partnerForm');
    const partnerSection = document.getElementById('partner');

    /**
     * Helper to trigger file downloads (TXT, JSON, and PDF)
     */
    function downloadApplication(data, format) {
        let fileName = `Application_${data.fullName.replace(/\s/g, '_')}`;

        if (format === 'pdf') {
            // PURE JS PDF APPROACH: Use a hidden print window
            const printWindow = window.open('', '_blank');
            printWindow.document.write(`
                <html>
                <head><title>${fileName}</title></head>
                <body style="font-family: Arial, sans-serif; padding: 40px; line-height: 1.6;">
                    <h1 style="color: #007bff; border-bottom: 2px solid #007bff;">Partner Application Summary</h1>
                    <p><strong>Submitted On:</strong> ${data.submittedAt}</p>
                    <hr>
                    <h3>Personal Information</h3>
                    <p><strong>Full Name:</strong> ${data.fullName}</p>
                    <p><strong>Email:</strong> ${data.email}</p>
                    <p><strong>Phone:</strong> ${data.phone}</p>
                    <p><strong>Country:</strong> ${data.country}</p>
                    <h3>Organization Details</h3>
                    <p><strong>Organization:</strong> ${data.orgName} (${data.orgType})</p>
                    <p><strong>Website:</strong> ${data.website || 'N/A'}</p>
                    <h3>Partnership Details</h3>
                    <p><strong>Planned Courses:</strong> ${data.courses}</p>
                    <p><strong>Experience:</strong> ${data.experience}</p>
                    <p><strong>Expertise Areas:</strong><br>${data.courseTopics}</p>
                    <footer style="margin-top: 50px; font-size: 0.8em; color: #888;">
                        Generated by Explorer Partner Portal
                    </footer>
                </body>
                </html>
            `);
            printWindow.document.close();
            printWindow.print(); // Browser will offer "Save as PDF"
            return;
        }

        // Standard logic for TXT and JSON
        let content = '';
        let mimeType = 'text/plain';

        if (format === 'json') {
            content = JSON.stringify(data, null, 4);
            fileName += '.json';
            mimeType = 'application/json';
        } else {
            content = `PARTNER APPLICATION SUMMARY\n===========================\nName: ${data.fullName}\nEmail: ${data.email}\nOrg: ${data.orgName}\nTopics: ${data.courseTopics}`;
            fileName += '.txt';
        }

        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        link.click();
        URL.revokeObjectURL(url);
    }

    partnerForm.addEventListener('submit', function(e) {
        e.preventDefault();
        const formData = new FormData(this);
        const data = Object.fromEntries(formData.entries());
        data.submittedAt = new Date().toLocaleString();
        data.status = "Pending Review";

        if (!data.terms) { alert("Please accept terms."); return; }

        const existingApps = JSON.parse(localStorage.getItem('partnerApps') || '[]');
        existingApps.push(data);
        localStorage.setItem('partnerApps', JSON.stringify(existingApps));

        showSummary(data);
    });

    function showSummary(record) {
        partnerForm.style.display = 'none';
        partnerSection.querySelector('h2').textContent = "Application Summary ✅";

        const summaryDiv = document.createElement('div');
        summaryDiv.className = 'summary-container';
        summaryDiv.style.cssText = `background: #f9f9f9; padding: 20px; border-radius: 8px; border-left: 5px solid #007bff;`;

        summaryDiv.innerHTML = `
            <h3>Thank you, ${record.fullName}!</h3>
            <p>Your application is received. <strong>Choose your format:</strong></p>
            
            <div style="margin: 15px 0; display: flex; flex-wrap: wrap; gap: 10px;">
                <button id="dl-pdf" style="padding: 8px 15px; background: #dc3545; color: white; border: none; border-radius: 4px; cursor: pointer;">Download PDF 📄</button>
                <button id="dl-txt" style="padding: 8px 15px; background: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer;">Download TXT</button>
                <button id="dl-json" style="padding: 8px 15px; background: #17a2b8; color: white; border: none; border-radius: 4px; cursor: pointer;">Download JSON</button>
            </div>
            <hr>
            <button onclick="window.location.reload()" style="margin-top: 20px; padding: 10px 20px; cursor: pointer;">Submit Another</button>
        `;

        partnerSection.appendChild(summaryDiv);

        document.getElementById('dl-pdf').addEventListener('click', () => downloadApplication(record, 'pdf'));
        document.getElementById('dl-txt').addEventListener('click', () => downloadApplication(record, 'txt'));
        document.getElementById('dl-json').addEventListener('click', () => downloadApplication(record, 'json'));
        
        partnerSection.scrollIntoView({ behavior: 'smooth' });
    }
});
